[package]
name = "permute"
version = "0.1.0"
authors = ["polymonster <alexandercdixon@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5.1"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "permute"
path = "permute.rs"
