[package]
name = "permute"
version = "0.1.0"
authors = ["polymonster <alexandercdixon@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"

[[bin]]
name = "permute"
path = "permute.rs"
