channels = [[ 
    {name = "x", index = 0}, 
    {name = "y", index = 1},
], [ 
    {name = "x", index = 0}, 
    {name = "y", index = 1},
], [ 
    {name = "x", index = 0}, 
    {name = "y", index = 1},
], [ 
    {name = "x", index = 0}, 
    {name = "y", index = 1},
]]

format_string = "Swizzle<T, 4, %i[0], %i[1], %i[2], %i[3]> %n[0]%n[1]%n[2]%n[3]; \\"