channels = [[ 
    {name = "x", index = 0}, 
    {name = "y", index = 1},
], [ 
    {name = "x", index = 0}, 
    {name = "y", index = 1}, 
]]

format_string = "Swizzle<T, 2, %d, %i[0], %i[1]> %n[0]%n[1]; \\"