channels = [[ 
    {name = "x", index = 0}, 
    {name = "y", index = 1}, 
    {name = "z", index = 2}, 
    {name = "w", index = 3}, 
], [ 
    {name = "x", index = 0}, 
    {name = "y", index = 1}, 
    {name = "z", index = 2}, 
    {name = "w", index = 3}, 
], [ 
    {name = "x", index = 0}, 
    {name = "y", index = 1}, 
    {name = "z", index = 2}, 
    {name = "w", index = 3}, 
]]

format_string = "Swizzle<T, 3, %d, %i[0], %i[1], %i[2], size_t(-1), size_t(-1)> %n[0]%n[1]%n[2]; \\"